# Import dependencies and data

In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import psycopg2
from config import db_password

from sklearn.model_selection import train_test_split
from imblearn.ensemble import BalancedRandomForestClassifier, EasyEnsembleClassifier
from imblearn.metrics import classification_report_imbalanced

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
#Load data
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/University_Salary"
engine = create_engine(db_string)

df = pd.read_sql_table("college_statistics",
                            con=engine)
df.head()

,Rank,University_Name,State,Region,Division,Early_Career_Pay,Mid_Career_Pay,Make_World_Better_Percent,Stem_Percent,Type,...,Black_Diversity_Percent,Hispanic_Diversity_Percent,Native_Hawaiian_Pacific_Islander_Diversity_Percent,Two_Or_More_Races_Diversity_Percent,Total_Minority_Diversity_Percent,Non-Resident_Foreign_Diversity_Percent,Unknown_Diversity_Percent,White_Diversity_Percent,Women_Diversity_Percent,Men_Diversity_Percent
0,1,Auburn University,Alabama,South,East South Central,54400,104500,51.0,31,Public,...,0.07,0.02,0.00,0.00,0.13,0.06,0.01,0.81,0.49,0.51
1,1,University Alaska Fairbanks,Alaska,West,Pacific,59100,101800,54.0,20,Public,...,0.02,0.05,0.00,0.04,0.24,0.03,0.28,0.45,0.58,0.42
2,1,Embry Riddle Aeronautical University Prescott,Arizona,West,Mountain,65600,117900,59.0,43,Private,...,0.02,0.06,0.01,0.09,0.23,0.10,0.10,0.57,0.23,0.77
3,1,University Arkansas,Arkansas,South,West South Central,52500,98000,49.0,18,Public,...,0.05,0.06,0.00,0.03,0.18,0.06,0.01,0.76,0.51,0.49
4,1,Harvey Mudd College,California,West,Pacific,88800,158200,55.0,85,Private,...,0.02,0.10,0.00,0.06,0.39,0.13,0.05,0.44,0.46,0.54

# Data cleaning and feature engineering

In [3]:
#Check column types and nulls
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 28 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Rank                                                907 non-null    int64
 1   University_Name                                     907 non-null    object
 2   State                                               907 non-null    object
 3   Region                                              907 non-null    object
 4   Division                                            907 non-null    object
 5   Early_Career_Pay                                    907 non-null    int64
 6   Mid_Career_Pay                                      907 non-null    int64
 7   Make_World_Better_Percent                           878 non-null    float64
 8   Stem_Percent                                        907 non-null    int64
 9   Type                                                907 non-null    object
 10  Degree_Length                                       907 non-null    object
 11  Room_And_Board                                      857 non-null    float64
 12  In_State_Tuition                                    907 non-null    int64
 13  In_State_Total                                      907 non-null    int64
 14  Out_Of_State_Tuition                                907 non-null    int64
 15  Out_Of_State_Total                                  907 non-null    int64
 16  American_Indian_Alaska_Native_Diversity_Percent     880 non-null    float64
 17  Asian_Diversity_Percent                             880 non-null    float64
 18  Black_Diversity_Percent                             880 non-null    float64
 19  Hispanic_Diversity_Percent                          880 non-null    float64
 20  Native_Hawaiian_Pacific_Islander_Diversity_Percent  880 non-null    float64
 21  Two_Or_More_Races_Diversity_Percent                 880 non-null    float64
 22  Total_Minority_Diversity_Percent                    880 non-null    float64
 23  Non-Resident_Foreign_Diversity_Percent              880 non-null    float64
 24  Unknown_Diversity_Percent                           880 non-null    float64
 25  White_Diversity_Percent                             880 non-null    float64
 26  Women_Diversity_Percent                             880 non-null    float64
 27  Men_Diversity_Percent                               880 non-null    float64
dtypes: float64(14), int64(8), object(6)
memory usage: 198.5+ KB

In [4]:
#Replace nulls with 0
df.fillna(0, inplace=True)

#Drop unnecessary columns and recheck column types and nulls
df = df.drop(columns=["University_Name","Rank","Mid_Career_Pay","Degree_Length"])

#Convert the target column values to low and medium/high income
def income(pay):
    if pay < 45000:
        return "Low"
    else:
        return "Medium/High"    

df["Early_Career_Pay"] = df.apply(lambda row: income(row["Early_Career_Pay"]), axis=1)

#Convert features to integers
df_binary = pd.get_dummies(df, columns=["Division","State","Region","Type"])

#Recheck column types and nulls
df_binary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 85 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Early_Career_Pay                                    907 non-null    object
 1   Make_World_Better_Percent                           907 non-null    float64
 2   Stem_Percent                                        907 non-null    int64
 3   Room_And_Board                                      907 non-null    float64
 4   In_State_Tuition                                    907 non-null    int64
 5   In_State_Total                                      907 non-null    int64
 6   Out_Of_State_Tuition                                907 non-null    int64
 7   Out_Of_State_Total                                  907 non-null    int64
 8   American_Indian_Alaska_Native_Diversity_Percent     907 non-null    float64
 9   Asian_Diversity_Percent                             907 non-null    float64
 10  Black_Diversity_Percent                             907 non-null    float64
 11  Hispanic_Diversity_Percent                          907 non-null    float64
 12  Native_Hawaiian_Pacific_Islander_Diversity_Percent  907 non-null    float64
 13  Two_Or_More_Races_Diversity_Percent                 907 non-null    float64
 14  Total_Minority_Diversity_Percent                    907 non-null    float64
 15  Non-Resident_Foreign_Diversity_Percent              907 non-null    float64
 16  Unknown_Diversity_Percent                           907 non-null    float64
 17  White_Diversity_Percent                             907 non-null    float64
 18  Women_Diversity_Percent                             907 non-null    float64
 19  Men_Diversity_Percent                               907 non-null    float64
 20  Division_East North Central                         907 non-null    uint8
 21  Division_East South Central                         907 non-null    uint8
 22  Division_Middle Atlantic                            907 non-null    uint8
 23  Division_Mountain                                   907 non-null    uint8
 24  Division_New England                                907 non-null    uint8
 25  Division_Pacific                                    907 non-null    uint8
 26  Division_South Atlantic                             907 non-null    uint8
 27  Division_West North Central                         907 non-null    uint8
 28  Division_West South Central                         907 non-null    uint8
 29  State_Alabama                                       907 non-null    uint8
 30  State_Alaska                                        907 non-null    uint8
 31  State_Arizona                                       907 non-null    uint8
 32  State_Arkansas                                      907 non-null    uint8
 33  State_California                                    907 non-null    uint8
 34  State_Colorado                                      907 non-null    uint8
 35  State_Connecticut                                   907 non-null    uint8
 36  State_Delaware                                      907 non-null    uint8
 37  State_Florida                                       907 non-null    uint8
 38  State_Georgia                                       907 non-null    uint8
 39  State_Hawaii                                        907 non-null    uint8
 40  State_Idaho                                         907 non-null    uint8
 41  State_Illinois                                      907 non-null    uint8
 42  State_Indiana                                       907 non-null    uint8
 43  State_Iowa                                          907 non-null    uint8
 44  State_Kansas                                        907 non-null    uint8
 45  State_Kentucky                                      907 non-null    uint8
 46  State_Louisiana                                     907 non-null    uint8
 47  State_Maine                                         907 non-null    uint8
 48  State_Maryland                                      907 non-null    uint8
 49  State_Massachusetts                                 907 non-null    uint8
 50  State_Michigan                                      907 non-null    uint8
 51  State_Minnesota                                     907 non-null    uint8
 52  State_Mississippi                                   907 non-null    uint8
 53  State_Missouri                                      907 non-null    uint8
 54  State_Montana                                       907 non-null    uint8
 55  State_Nebraska                                      907 non-null    uint8
 56  State_Nevada                                        907 non-null    uint8
 57  State_New Hampshire                                 907 non-null    uint8
 58  State_New Jersey                                    907 non-null    uint8
 59  State_New Mexico                                    907 non-null    uint8
 60  State_New York                                      907 non-null    uint8
 61  State_North Carolina                                907 non-null    uint8
 62  State_North Dakota                                  907 non-null    uint8
 63  State_Ohio                                          907 non-null    uint8
 64  State_Oklahoma                                      907 non-null    uint8
 65  State_Oregon                                        907 non-null    uint8
 66  State_Pennsylvania                                  907 non-null    uint8
 67  State_Rhode Island                                  907 non-null    uint8
 68  State_South Carolina                                907 non-null    uint8
 69  State_South Dakota                                  907 non-null    uint8
 70  State_Tennessee                                     907 non-null    uint8
 71  State_Texas                                         907 non-null    uint8
 72  State_Utah                                          907 non-null    uint8
 73  State_Vermont                                       907 non-null    uint8
 74  State_Virginia                                      907 non-null    uint8
 75  State_Washington                                    907 non-null    uint8
 76  State_West Virginia                                 907 non-null    uint8
 77  State_Wisconsin                                     907 non-null    uint8
 78  State_Wyoming                                       907 non-null    uint8
 79  Region_Midwest                                      907 non-null    uint8
 80  Region_Northeast                                    907 non-null    uint8
 81  Region_South                                        907 non-null    uint8
 82  Region_West                                         907 non-null    uint8
 83  Type_Private                                        907 non-null    uint8
 84  Type_Public                                         907 non-null    uint8
dtypes: float64(14), int64(5), object(1), uint8(65)
memory usage: 199.4+ KB

# Create features and target and split into training and testing

In [5]:
#Create features and target
X = df_binary.drop(columns="Early_Career_Pay")
y = df_binary["Early_Career_Pay"]

y.value_counts()

Medium/High    719
Low            188
Name: Early_Career_Pay, dtype: int64

In [6]:
#Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)

# Balanced Random Forest Classifier

In [7]:
#Create Logistic Regression model and train the data
clf = BalancedRandomForestClassifier(random_state=1).fit(X_train, y_train)

#Predict outcomes for test data set
y_pred = clf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

C:\Users\jumok\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name', 'str']. An error will be raised in 1.2.
  FutureWarning,
C:\Users\jumok\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name', 'str']. An error will be raised in 1.2.
  FutureWarning,

0.8570282045402431

In [8]:
#Confusion maxtrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[ 46   3]
 [ 40 138]]

In [9]:
#Classification report
report = classification_report_imbalanced(y_test, y_pred)
print(report)

                   pre       rec       spe        f1       geo       iba       sup

        Low       0.53      0.94      0.78      0.68      0.85      0.74        49
Medium/High       0.98      0.78      0.94      0.87      0.85      0.72       178

avg / total       0.88      0.81      0.90      0.83      0.85      0.72       227

In [10]:
# List the features sorted in descending order by feature importance
features = clf.feature_importances_
print(features)

[3.96870488e-02 7.00904371e-02 9.41201684e-02 7.06579049e-02
 4.56666220e-02 5.43584700e-02 6.16393807e-02 2.27520810e-02
 1.25512777e-01 3.13486775e-02 2.97793699e-02 4.07576084e-03
 2.01066199e-02 2.33283214e-02 4.32023084e-02 2.23204993e-02
 2.67454381e-02 3.65198278e-02 3.10547472e-02 1.78826364e-02
 8.08113870e-03 3.70976529e-03 3.96179497e-03 1.34731857e-03
 1.79330142e-03 3.26803382e-03 4.22841532e-03 4.49561916e-03
 2.42348702e-03 5.08964896e-04 5.71711502e-05 2.89229019e-03
 8.07076703e-04 7.36880390e-04 7.29914091e-04 3.74563336e-04
 2.26169237e-03 3.41538542e-03 7.57552715e-04 1.45118867e-03
 4.74211860e-04 4.46574009e-04 7.78234121e-04 4.42303814e-03
 2.26422948e-03 4.80145369e-04 1.94361216e-03 7.07206387e-04
 1.03730079e-04 2.91135403e-03 1.84212103e-03 1.26930473e-03
 9.61728415e-04 2.05549846e-04 8.69100033e-04 1.90397463e-04
 7.33091696e-04 5.23033808e-04 3.88105542e-05 2.02882305e-04
 3.43397699e-03 6.81715710e-04 1.52408091e-03 9.38843396e-04
 2.12050804e-03 5.41071607e-04 2.94347878e-04 3.49612810e-03
 1.01456855e-03 2.69158214e-03 1.12843887e-03 1.38646784e-03
 1.81734924e-03 1.92751216e-03 7.27335703e-04 3.12410135e-03
 1.89576121e-03 0.00000000e+00 4.43761865e-03 2.16982021e-03
 8.48247899e-03 3.01643836e-03 7.59550079e-03 6.03534723e-03]

In [11]:
pd.options.display.max_rows = 100

features = pd.DataFrame(clf.feature_importances_, index=X.columns, columns=['feature importance']).sort_values('feature importance', ascending=False)
features

                                                    feature importance
Asian_Diversity_Percent                                       0.125513
Room_And_Board                                                0.094120
In_State_Tuition                                              0.070658
Stem_Percent                                                  0.070090
Out_Of_State_Total                                            0.061639
Out_Of_State_Tuition                                          0.054358
In_State_Total                                                0.045667
Non-Resident_Foreign_Diversity_Percent                        0.043202
Make_World_Better_Percent                                     0.039687
Women_Diversity_Percent                                       0.036520
Black_Diversity_Percent                                       0.031349
Men_Diversity_Percent                                         0.031055
Hispanic_Diversity_Percent                                    0.029779
White_Diversity_Percent                                       0.026745
Total_Minority_Diversity_Percent                              0.023328
American_Indian_Alaska_Native_Diversity_Percent               0.022752
Unknown_Diversity_Percent                                     0.022320
Two_Or_More_Races_Diversity_Percent                           0.020107
Division_East North Central                                   0.017883
Region_South                                                  0.008482
Division_East South Central                                   0.008081
Type_Private                                                  0.007596
Type_Public                                                   0.006035
Division_West South Central                                   0.004496
Region_Midwest                                                0.004438
State_Kansas                                                  0.004423
Division_West North Central                                   0.004228
Native_Hawaiian_Pacific_Islander_Diversity_Percent            0.004076
Division_Mountain                                             0.003962
Division_Middle Atlantic                                      0.003710
State_South Carolina                                          0.003496
State_North Carolina                                          0.003434
State_Georgia                                                 0.003415
Division_South Atlantic                                       0.003268
State_West Virginia                                           0.003124
Region_West                                                   0.003016
State_Michigan                                                0.002911
State_Arkansas                                                0.002892
State_Tennessee                                               0.002692
State_Alabama                                                 0.002423
State_Kentucky                                                0.002264
State_Florida                                                 0.002262
Region_Northeast                                              0.002170
State_Oregon                                                  0.002121
State_Maine                                                   0.001944
State_Virginia                                                0.001928
State_Wisconsin                                               0.001896
State_Minnesota                                               0.001842
State_Vermont                                                 0.001817
Division_Pacific                                              0.001793
State_Ohio                                                    0.001524
State_Idaho                                                   0.001451
State_Utah                                                    0.001386
Division_New England                                          0.001347
State_Mississippi                                             0.001269
State_Texas                                                   0.001128
State_South Dakota                                            0.001015
State_Missouri                                                0.000962
State_Oklahoma                                                0.000939
State_Nebraska                                                0.000869
State_California                                              0.000807
State_Iowa                                                    0.000778
State_Hawaii                                                  0.000758
State_Colorado                                                0.000737
State_New Hampshire                                           0.000733
State_Connecticut                                             0.000730
State_Washington                                              0.000727
State_Maryland                                                0.000707
State_North Dakota                                            0.000682
State_Pennsylvania                                            0.000541
State_New Jersey                                              0.000523
State_Alaska                                                  0.000509
State_Louisiana                                               0.000480
State_Illinois                                                0.000474
State_Indiana                                                 0.000447
State_Delaware                                                0.000375
State_Rhode Island                                            0.000294
State_Montana                                                 0.000206
State_New York                                                0.000203
State_Nevada                                                  0.000190
State_Massachusetts                                           0.000104
State_Arizona                                                 0.000057
State_New Mexico                                              0.000039
State_Wyoming                                                 0.000000

# Easy Ensemble AdaBoost Classifier

In [12]:
# Train the EasyEnsembleClassifier
ada_clf = EasyEnsembleClassifier(random_state=1,n_estimators=100).fit(X_train, y_train)

C:\Users\jumok\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [13]:
# Calculate the balanced accuracy score for Easy Ensemble
y_pred = ada_clf.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

C:\Users\jumok\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name', 'str']. An error will be raised in 1.2.
  FutureWarning,

0.8616143086448063

In [14]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 47,   2],
       [ 42, 136]], dtype=int64)

In [15]:
# Print the imbalanced classification report for Easy Ensemble
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

        Low       0.53      0.96      0.76      0.68      0.86      0.75        49
Medium/High       0.99      0.76      0.96      0.86      0.86      0.72       178

avg / total       0.89      0.81      0.92      0.82      0.86      0.72       227